export const ActionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  SINGLE_PRODUCT: "SINGLE_PRODUCT",
  REMOVE_CHOOSING: "REMOVE_CHOOSING",
  GET_USERS: "GET_USERS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRODUCTS_BY_CATEGORY: "GET_PRODUCTS_BY_CATEGORY",
  REMOVE_SELECTED_CATEGORY: "REMOVE_SELECTED_CATEGORY",
};
